# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncrawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('node', 'name')]),
        ),
    ]
