# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncrawl', '0002_auto_20170312_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='driver',
            field=models.CharField(default=b'ios', max_length=20),
        ),
    ]
